services:
  complainer_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - complainer_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  complainer_cache:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - complainer_cache:/data/

volumes:
  complainer_db:
  complainer_cache:
